apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.global.metadata.name }}-configmap"
  namespace: {{ .Values.global.metadata.namespace }}
  labels:
    {{- if .Values.global.configMap.labels }}
    {{- toYaml .Values.global.configMap.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.configMap.annotations }}
    {{- toYaml .Values.global.configMap.annotations | nindent 4 }}
    {{- end }}
data:
  # Deployment / Proxy Infrastructure Settings
  deployment: |
    spec:
      {{- if .Values.global.configMap.data.deployment.replicas }}
      replicas: {{ .Values.global.configMap.data.deployment.replicas }}
      {{- end }}
      {{- if .Values.global.configMap.data.deployment.strategy }}
      strategy:
        {{- toYaml .Values.global.configMap.data.deployment.strategy | nindent 8 }}
      {{- end }}
      template:
        {{- if or .Values.global.configMap.data.deployment.podLabels .Values.global.configMap.data.deployment.podAnnotations }}
        metadata:
          {{- if .Values.global.configMap.data.deployment.podLabels }}
          labels:
            {{- toYaml .Values.global.configMap.data.deployment.podLabels | nindent 12 }}
          {{- end }}
          {{- if .Values.global.configMap.data.deployment.podAnnotations }}
          annotations:
            {{- toYaml .Values.global.configMap.data.deployment.podAnnotations | nindent 12 }}
          {{- end }}
        {{- end }}
        spec:
          {{- if .Values.global.configMap.data.deployment.serviceAccountName }}
          serviceAccountName: {{ .Values.global.configMap.data.deployment.serviceAccountName | quote }}
          {{- end }}
          {{- if .Values.global.configMap.data.deployment.priorityClassName }}
          priorityClassName: {{ .Values.global.configMap.data.deployment.priorityClassName | quote }}
          {{- end }}
          {{- if .Values.global.configMap.data.deployment.securityContext }}
          securityContext:
            {{- toYaml .Values.global.configMap.data.deployment.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.global.configMap.data.deployment.tolerations }}
          tolerations:
            {{- toYaml .Values.global.configMap.data.deployment.tolerations | nindent 12 }}
          {{- end }}
          {{- if .Values.global.configMap.data.deployment.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml .Values.global.configMap.data.deployment.topologySpreadConstraints | nindent 12 }}
          {{- end }}
          {{- if .Values.global.configMap.data.deployment.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.global.configMap.data.deployment.nodeSelector | nindent 12 }}
          {{- end }}
          affinity:
            {{- if .Values.global.configMap.data.deployment.nodeAffinity }}
            {{- $nodeAffinity := .Values.global.configMap.data.deployment.nodeAffinity }}
            nodeAffinity:
              {{- if $nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution }}
              requiredDuringSchedulingIgnoredDuringExecution:
                {{- toYaml $nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 16 }}
              {{- end }}
              {{- if $nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
              preferredDuringSchedulingIgnoredDuringExecution:
                {{- toYaml $nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.configMap.data.deployment.podAffinity }}
            podAffinity:
              {{- toYaml .Values.global.configMap.data.deployment.podAffinity | nindent 14 }}
            {{- end }}
            {{- if .Values.global.configMap.data.deployment.podAntiAffinity }}
            podAntiAffinity:
              {{- toYaml .Values.global.configMap.data.deployment.podAntiAffinity | nindent 14 }}
            {{- end }}
          {{- if .Values.global.configMap.data.deployment.containers }}
          containers:
            {{- toYaml .Values.global.configMap.data.deployment.containers | nindent 12 }}
          {{- end }}

  # Service / Cloud Load Balancer Configurations
  service: |
    spec:
      {{- if .Values.global.configMap.data.service.type }}
      type: {{ .Values.global.configMap.data.service.type }}
      {{- end }}
      {{- if .Values.global.configMap.data.service.externalTrafficPolicy }}
      externalTrafficPolicy: {{ .Values.global.configMap.data.service.externalTrafficPolicy }}
      {{- end }}
      {{- if .Values.global.configMap.data.service.loadBalancerClass }}
      loadBalancerClass: {{ .Values.global.configMap.data.service.loadBalancerClass | quote }}
      {{- end }}
      {{- if .Values.global.configMap.data.service.loadBalancerIP }}
      loadBalancerIP: {{ .Values.global.configMap.data.service.loadBalancerIP | quote }}
      {{- end }}
      {{- if .Values.global.configMap.data.service.loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
        {{- toYaml .Values.global.configMap.data.service.loadBalancerSourceRanges | nindent 8 }}
      {{- end }}
      {{- if .Values.global.configMap.data.service.annotations }}
      annotations:
        {{- toYaml .Values.global.configMap.data.service.annotations | nindent 8 }}
      {{- end }}

  # Advanced Gateway / Proxy Runtime Configurations
  proxyConfig: |
    {{- if .Values.global.configMap.data.proxyConfig }}
    {{- toYaml .Values.global.configMap.data.proxyConfig | nindent 4 }}
    {{- end }}