{{- if .Values.global.tlsSecret.enabled }}
{{- if eq .Values.global.tlsSecret.type "cert-manager" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.tlsSecret.name }}
  namespace: {{ .Values.global.metadata.namespace }}
spec:
  secretName: {{ .Values.global.tlsSecret.secretName }}
  issuerRef:
    name: {{ .Values.global.tlsSecret.certManager.issuerName }}
    kind: {{ .Values.global.tlsSecret.certManager.issuerKind | default "ClusterIssuer" }}
  dnsNames:
    {{- toYaml .Values.global.tlsSecret.certManager.dnsNames | nindent 4 }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tlsSecret.secretName }}
  namespace: {{ .Values.global.metadata.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.tlsSecret.crt | b64enc | quote }}
  tls.key: {{ .Values.global.tlsSecret.key | b64enc | quote }}
{{- end }}
{{- end }}